version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-stretch
    working_directory: ~/asobicoin
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install NPM packages
          command: npm install
      - run:
          name: Run linters
          command: npm run lint
      - run:
          name: Run tests
          command: npm test
      - save_cache:
          paths:
            - ~/asobicoin/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
